### ISSUE TITLE
GIT_REPOSITORY_REGEX should accept more repo url's 

### ISSUE THREAD

**Issue by stefan52a** [significa/1password-secrets#16]
My gitea ssh repos start with ssh: instead of git:
So I am trying to propose a pull request for that.

**Comment by tofran** [comment]
Hello @stefan52a, we have made the fix and published it as [0.0.1.dev79 ](https://pypi.org/project/1password-secrets/0.0.1.dev79/)
While we don't create a new release, test it with `pip install 1password-secrets==0.0.1.dev79`

**Comment by stefan52a** [comment]
Okay, thank you. A bit more complex than if you would just create a git branch for that. I will try to find some time to test it this way.

**Comment by tofran** [comment]
No worries, for me this was automatic. 

Check out the new release in [v0.0.8](https://github.com/significa/1password-secrets/releases/tag/v0.0.8)
